// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoiNuQRN5S7606VhdZrVq9OPiaXe-sEiU',
    appId: '1:759351128993:web:1c4894b0c095339c3e51e0',
    messagingSenderId: '759351128993',
    projectId: 'my-scholar-5fca8',
    authDomain: 'my-scholar-5fca8.firebaseapp.com',
    storageBucket: 'my-scholar-5fca8.appspot.com',
    measurementId: 'G-812T2M33CE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPCcZkAd8HCp5SrfX0bq0iUxa3y-teb50',
    appId: '1:759351128993:android:0590a7ebded707dc3e51e0',
    messagingSenderId: '759351128993',
    projectId: 'my-scholar-5fca8',
    storageBucket: 'my-scholar-5fca8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8kSzLZy7rIwPtDBVc6CjH9YeXQd3oXnw',
    appId: '1:759351128993:ios:e1efc105f9ad4fef3e51e0',
    messagingSenderId: '759351128993',
    projectId: 'my-scholar-5fca8',
    storageBucket: 'my-scholar-5fca8.appspot.com',
    iosBundleId: 'com.aas.myScholar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8kSzLZy7rIwPtDBVc6CjH9YeXQd3oXnw',
    appId: '1:759351128993:ios:e1efc105f9ad4fef3e51e0',
    messagingSenderId: '759351128993',
    projectId: 'my-scholar-5fca8',
    storageBucket: 'my-scholar-5fca8.appspot.com',
    iosBundleId: 'com.aas.myScholar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoiNuQRN5S7606VhdZrVq9OPiaXe-sEiU',
    appId: '1:759351128993:web:f5c76fb6420a9d203e51e0',
    messagingSenderId: '759351128993',
    projectId: 'my-scholar-5fca8',
    authDomain: 'my-scholar-5fca8.firebaseapp.com',
    storageBucket: 'my-scholar-5fca8.appspot.com',
    measurementId: 'G-40J107BJDF',
  );
}
